/* The following code was generated by JFlex 1.4.3 on 19.04.19, 14:27 */

package de.invesdwin.context.client.swing.rsyntaxtextarea.expression.internal;

import java.io.IOException;
import java.io.Reader;

import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexCTokenMaker;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenImpl;

// CHECKSTYLE:OFF
// @NotThreadSafe

/**
 * This class is a scanner generated by <a href="http://www.jflex.de/">JFlex</a> 1.4.3 on 19.04.19, 14:27 from the
 * specification file
 * <tt>/opt/subes/dev/Entwicklung/invesdwin/invesdwin-oss/invesdwin-context-client/invesdwin-context-client-parent/invesdwin-context-client-swing-rsyntaxtextarea/src/main/java/de/invesdwin/context/client/swing/rsyntaxtextarea/expression/internal/ExpressionTokenMaker.flex</tt>
 */
public abstract class AExpressionTokenMaker extends AbstractJFlexCTokenMaker {

    /** This character denotes the end of file */
    public static final int YYEOF = -1;

    /** initial size of the lookahead buffer */
    private static final int ZZ_BUFFERSIZE = 16384;

    /** lexical states */
    public static final int EOL_COMMENT = 6;
    public static final int DOCCOMMENT = 4;
    public static final int YYINITIAL = 0;
    public static final int MLC = 2;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l ZZ_LEXSTATE[l+1] is the state in the DFA for the
     * lexical state l at the beginning of a line l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = { 0, 0, 1, 1, 2, 2, 3, 3 };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED = "\11\0\1\22\1\11\1\0\1\22\1\20\22\0\1\22\1\52\1\16"
            + "\1\21\1\21\1\52\1\55\1\10\2\45\1\24\1\47\1\46\1\33" + "\1\34\1\23\1\4\1\5\2\17\4\7\2\3\1\54\1\46\1\50"
            + "\1\51\1\53\1\54\1\56\1\43\1\26\1\6\1\31\1\32\1\42" + "\5\1\1\25\1\1\1\57\1\60\2\1\1\37\1\44\1\35\1\41"
            + "\2\1\1\30\2\1\1\45\1\12\1\45\1\52\1\2\1\0\1\43" + "\1\27\1\6\1\31\1\32\1\15\1\1\1\61\3\1\1\25\1\1"
            + "\1\14\1\60\2\1\1\40\1\44\1\36\1\13\1\1\1\61\1\30" + "\2\1\1\62\1\52\1\45\1\54\uff81\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 = "\4\0\1\1\1\2\2\3\1\4\1\5\1\2\1\6"
            + "\1\1\1\7\3\10\3\2\1\11\1\2\5\10\1\12" + "\1\2\1\13\1\14\3\13\1\15\3\13\1\16\1\1"
            + "\2\17\1\20\1\3\1\17\1\20\2\17\1\21\2\17" + "\1\4\1\22\1\0\1\4\1\2\2\6\1\23\1\24"
            + "\1\25\2\2\1\0\1\10\1\12\1\26\1\27\1\30" + "\2\0\1\31\1\1\1\3\1\20\1\0\2\21\1\3"
            + "\1\21\1\4\1\32\2\4\1\22\1\4\1\2\1\6" + "\1\33\1\6\1\34\1\2\2\1\2\17\1\4\1\6"
            + "\1\35\1\36\2\1\1\4\1\6\2\1\1\4\1\6" + "\2\1";

    private static int[] zzUnpackAction() {
        final int[] result = new int[110];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            final int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 = "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"
            + "\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u01cb\0\u0264\0\u0297\0\u02ca"
            + "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u01cb\0\u01cb\0\u03c9\0\u03fc"
            + "\0\u042f\0\u01cb\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u01cb\0\u01cb"
            + "\0\u052e\0\u0561\0\u01cb\0\u0594\0\u05c7\0\u05fa\0\u01cb\0\u062d"
            + "\0\u0660\0\u0693\0\u0660\0\u0660\0\u06c6\0\u06f9\0\u072c\0\u075f"
            + "\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u01cb\0\u085e\0\u0891\0\u08c4"
            + "\0\u08f7\0\u092a\0\u01cb\0\u01cb\0\u095d\0\u0990\0\u09c3\0\u02ca"
            + "\0\u09f6\0\u0a29\0\377\0\u01cb\0\u01cb\0\u0a5c\0\u0a8f\0\u01cb"
            + "\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0660\0\u0bc1\0\u0bf4"
            + "\0\u0c27\0\u01cb\0\u0c5a\0\u0c8d\0\u085e\0\u0cc0\0\u0cf3\0\u0d26"
            + "\0\u01cb\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0bc1\0\u0e58"
            + "\0\u0e8b\0\u0ebe\0\u01cb\0\377\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a"
            + "\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc";

    private static int[] zzUnpackRowMap() {
        final int[] result = new int[110];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            final int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 = "\1\5\2\6\1\7\1\10\1\7\1\6\1\7\1\11"
            + "\1\12\1\5\2\6\1\13\1\14\1\7\1\15\1\6" + "\1\16\1\17\1\20\6\6\1\21\1\22\2\23\3\6"
            + "\1\13\1\24\1\6\1\25\1\26\1\27\1\30\2\20" + "\1\31\1\32\1\33\1\34\1\6\1\35\1\6\1\25"
            + "\11\36\1\37\3\36\1\40\6\36\1\41\34\36\1\40" + "\1\36\11\42\1\43\3\42\1\40\6\42\1\44\23\42"
            + "\1\45\5\42\1\0\2\42\2\40\11\46\1\47\3\46" + "\1\40\43\46\1\40\1\46\10\5\2\0\4\5\1\0"
            + "\1\5\1\0\1\5\3\0\6\5\2\0\10\5\11\0" + "\4\5\1\0\1\5\7\6\2\0\1\50\3\6\1\0"
            + "\1\6\1\0\1\6\3\0\6\6\2\0\10\6\11\0" + "\1\5\3\6\1\0\2\51\1\52\3\7\1\51\1\7"
            + "\2\0\3\51\1\53\1\0\1\7\1\0\1\51\3\0" + "\1\54\3\51\1\53\1\55\1\0\1\56\5\51\1\53"
            + "\2\51\11\0\4\51\1\0\2\51\1\57\1\60\2\61" + "\1\51\1\61\2\0\3\51\1\53\1\0\1\61\1\0"
            + "\1\51\3\0\1\54\2\62\1\63\1\53\1\55\1\0" + "\1\56\5\51\1\53\2\51\11\0\4\51\1\0\10\64"
            + "\1\65\1\66\1\67\50\64\63\0\1\5\7\6\2\0" + "\1\50\3\6\1\0\1\6\1\0\1\6\3\0\6\6"
            + "\2\0\6\6\1\70\1\6\11\0\1\5\3\6\1\0" + "\11\14\1\71\1\72\3\14\1\73\44\14\22\0\1\16"
            + "\63\0\1\74\1\75\24\0\1\32\62\0\1\32\44\0" + "\1\32\15\0\1\32\14\0\3\56\1\0\1\56\7\0"
            + "\1\56\43\0\1\5\7\6\2\0\1\50\3\6\1\0" + "\1\6\1\0\1\6\3\0\6\6\2\0\2\6\2\76"
            + "\4\6\11\0\1\5\3\6\1\0\1\5\7\6\2\0" + "\1\50\1\6\1\77\1\6\1\0\1\6\1\0\1\6"
            + "\3\0\6\6\2\0\10\6\11\0\1\5\1\77\2\6" + "\50\0\1\32\1\0\1\32\61\0\1\100\1\32\1\0"
            + "\1\32\57\0\2\32\1\0\1\101\60\0\1\32\3\0" + "\1\32\5\0\1\5\2\102\3\5\1\102\1\5\2\0"
            + "\1\5\3\102\1\0\1\5\1\0\1\102\3\0\6\102" + "\2\0\10\102\11\0\1\5\3\102\1\0\1\5\7\6"
            + "\2\0\1\50\3\6\1\0\1\6\1\0\1\6\3\0" + "\6\6\2\0\2\6\2\103\4\6\11\0\1\5\3\6"
            + "\1\0\11\36\1\0\3\36\1\0\6\36\1\0\34\36" + "\1\0\1\36\23\0\1\104\37\0\11\42\1\0\3\42"
            + "\1\0\6\42\1\0\23\42\1\0\5\42\1\0\2\42" + "\25\0\1\105\40\0\1\106\4\0\1\106\4\0\3\106"
            + "\5\0\1\107\1\0\6\106\2\0\10\106\6\0\1\110" + "\3\0\3\106\1\0\11\46\1\0\3\46\1\0\43\46"
            + "\1\0\1\46\10\5\2\0\1\5\1\111\2\5\1\0" + "\1\5\1\0\1\5\3\0\6\5\2\0\10\5\11\0"
            + "\4\5\1\0\10\51\2\0\4\51\1\0\1\51\1\0" + "\1\51\3\0\6\51\2\0\10\51\11\0\4\51\1\0"
            + "\2\51\1\52\3\112\1\51\1\112\2\0\4\51\1\0" + "\1\112\1\0\1\51\3\0\6\51\2\0\10\51\11\0"
            + "\4\51\1\0\3\51\3\113\1\51\1\113\2\0\4\51" + "\1\0\1\113\1\0\1\51\3\0\6\51\1\114\1\0"
            + "\10\51\2\0\1\114\6\0\4\51\1\0\3\51\3\56" + "\1\51\1\56\2\0\3\51\1\53\1\0\1\56\1\0"
            + "\1\51\3\0\4\51\1\53\1\55\2\0\5\51\1\53" + "\2\51\11\0\4\51\1\0\2\51\1\57\1\51\2\115"
            + "\1\51\1\115\2\0\4\51\1\0\1\115\1\0\1\51" + "\3\0\6\51\2\0\10\51\11\0\4\51\1\0\3\51"
            + "\3\60\1\51\1\60\2\0\3\51\1\53\1\0\1\60" + "\1\0\1\51\3\0\4\51\1\53\1\55\1\0\1\56"
            + "\5\51\1\53\2\51\11\0\4\51\1\0\2\51\1\57" + "\1\60\2\61\1\51\1\61\2\0\3\51\1\53\1\0"
            + "\1\61\1\0\1\51\3\0\1\116\3\51\1\53\1\55" + "\1\0\1\56\5\51\1\53\2\51\11\0\4\51\1\0"
            + "\4\51\2\117\2\51\2\0\4\51\1\0\1\51\1\0" + "\1\51\3\0\6\51\2\0\10\51\11\0\4\51\1\0"
            + "\3\51\5\120\2\0\3\51\1\120\1\0\1\120\1\0" + "\1\51\3\0\1\51\2\120\1\51\2\120\2\0\5\51"
            + "\2\120\1\51\11\0\4\51\1\0\10\121\1\122\1\0" + "\51\121\10\0\1\122\52\0\4\121\2\123\1\121\1\124"
            + "\1\125\1\0\1\64\1\126\3\64\1\123\7\121\1\64" + "\6\121\1\64\1\121\1\64\22\121\1\5\7\6\2\0"
            + "\1\50\3\6\1\0\1\6\1\0\1\6\3\0\1\127" + "\5\6\2\0\10\6\11\0\1\5\3\6\1\0\12\71"
            + "\1\130\3\71\1\131\50\71\2\14\1\71\2\14\1\0" + "\1\14\1\132\4\14\7\71\1\14\6\71\1\14\1\71"
            + "\1\14\22\71\24\0\1\133\36\0\1\5\7\6\2\0" + "\1\50\1\134\2\6\1\0\1\6\1\0\1\6\3\0"
            + "\6\6\2\0\4\6\1\134\3\6\11\0\1\5\3\6" + "\1\0\1\5\7\6\2\0\1\50\3\6\1\0\1\6"
            + "\1\0\1\6\3\0\4\6\1\103\1\6\2\0\10\6" + "\11\0\1\5\3\6\52\0\1\32\1\0\1\20\7\0"
            + "\1\5\7\102\2\0\1\135\3\102\1\0\1\102\1\0" + "\1\102\3\0\6\102\2\0\10\102\11\0\1\5\3\102"
            + "\1\0\53\106\1\110\7\106\1\0\1\106\4\0\1\106" + "\4\0\3\106\7\0\6\106\2\0\10\106\6\0\1\110"
            + "\3\0\3\106\1\0\3\5\5\136\2\0\3\5\1\136" + "\1\0\1\136\1\0\1\5\3\0\1\5\2\136\1\5"
            + "\2\136\2\0\5\5\2\136\1\5\11\0\4\5\1\0" + "\2\51\1\52\3\112\1\51\1\112\2\0\4\51\1\0"
            + "\1\112\1\0\1\51\3\0\1\54\5\51\2\0\10\51" + "\11\0\4\51\1\0\3\51\3\113\1\51\1\113\2\0"
            + "\3\51\1\53\1\0\1\113\1\0\1\51\3\0\4\51" + "\1\53\1\51\2\0\5\51\1\53\2\51\11\0\4\51"
            + "\4\0\3\113\1\0\1\113\7\0\1\113\43\0\2\51" + "\1\57\1\51\2\115\1\51\1\115\2\0\4\51\1\0"
            + "\1\115\1\0\1\51\3\0\1\116\5\51\2\0\10\51" + "\11\0\4\51\1\0\2\51\1\137\1\51\2\117\2\51"
            + "\2\0\4\51\1\0\1\51\1\0\1\51\3\0\6\51" + "\2\0\10\51\11\0\4\51\1\0\2\51\1\140\5\120"
            + "\2\0\3\51\1\120\1\0\1\120\1\0\1\51\3\0" + "\1\116\2\120\1\51\2\120\2\0\5\51\2\120\1\51"
            + "\11\0\4\51\1\0\10\121\1\65\1\0\55\121\2\124" + "\1\121\1\124\1\122\1\0\5\121\1\124\47\121\2\64"
            + "\1\121\1\64\1\122\1\0\5\121\1\64\46\121\5\141" + "\1\65\1\0\3\121\1\141\1\121\1\141\6\121\2\141"
            + "\1\121\2\141\7\121\2\141\17\121\1\5\7\6\2\0" + "\1\50\3\6\1\0\1\6\1\0\1\6\3\0\6\6"
            + "\2\0\7\6\1\134\11\0\1\5\3\6\1\0\11\71" + "\1\0\54\71\5\142\2\71\1\130\2\71\1\142\1\131"
            + "\1\142\6\71\2\142\1\71\2\142\7\71\2\142\17\71" + "\23\0\1\143\37\0\1\5\7\6\2\0\1\50\3\6"
            + "\1\0\1\6\1\0\1\6\3\0\5\6\1\144\2\0" + "\10\6\11\0\1\5\3\6\1\0\10\5\2\0\1\5"
            + "\1\145\2\5\1\0\1\5\1\0\1\5\3\0\6\5" + "\2\0\10\5\11\0\4\5\1\0\3\5\5\146\2\0"
            + "\3\5\1\146\1\0\1\146\1\0\1\5\3\0\1\5" + "\2\146\1\5\2\146\2\0\5\5\2\146\1\5\11\0"
            + "\4\5\1\0\2\51\1\140\5\120\2\0\3\51\1\120" + "\1\0\1\120\1\0\1\51\3\0\1\51\2\120\1\51"
            + "\2\120\2\0\5\51\2\120\1\51\11\0\4\51\1\0" + "\3\121\5\147\1\65\1\0\3\121\1\147\1\121\1\147"
            + "\6\121\2\147\1\121\2\147\7\121\2\147\17\121\3\71" + "\5\150\2\71\1\130\2\71\1\150\1\131\1\150\6\71"
            + "\2\150\1\71\2\150\7\71\2\150\17\71\3\5\5\151" + "\2\0\3\5\1\151\1\0\1\151\1\0\1\5\3\0"
            + "\1\5\2\151\1\5\2\151\2\0\5\5\2\151\1\5" + "\11\0\4\5\1\0\3\5\5\152\2\0\3\5\1\152"
            + "\1\0\1\152\1\0\1\5\3\0\1\5\2\152\1\5" + "\2\152\2\0\5\5\2\152\1\5\11\0\4\5\1\0"
            + "\3\121\5\153\1\65\1\0\3\121\1\153\1\121\1\153" + "\6\121\2\153\1\121\2\153\7\121\2\153\17\121\3\71"
            + "\5\154\2\71\1\130\2\71\1\154\1\131\1\154\6\71" + "\2\154\1\71\2\154\7\71\2\154\17\71\3\5\5\155"
            + "\2\0\3\5\1\155\1\0\1\155\1\0\1\5\3\0" + "\1\5\2\155\1\5\2\155\2\0\5\5\2\155\1\5"
            + "\11\0\4\5\1\0\3\5\5\6\2\0\3\5\1\6" + "\1\0\1\6\1\0\1\5\3\0\1\5\2\6\1\5"
            + "\2\6\2\0\5\5\2\6\1\5\11\0\4\5\1\0" + "\3\121\5\64\1\65\1\0\3\121\1\64\1\121\1\64"
            + "\6\121\2\64\1\121\2\64\7\121\2\64\17\121\3\71" + "\5\14\2\71\1\130\2\71\1\14\1\131\1\14\6\71"
            + "\2\14\1\71\2\14\7\71\2\14\17\71\3\5\5\156" + "\2\0\3\5\1\156\1\0\1\156\1\0\1\5\3\0"
            + "\1\5\2\156\1\5\2\156\2\0\5\5\2\156\1\5" + "\11\0\4\5\1\0\3\5\5\102\2\0\3\5\1\102"
            + "\1\0\1\102\1\0\1\5\3\0\1\5\2\102\1\5" + "\2\102\2\0\5\5\2\102\1\5\11\0\4\5\1\0";

    private static int[] zzUnpackTrans() {
        final int[] result = new int[4335];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = { "Unkown internal scanner error", "Error: could not match input",
            "Error: pushback value was too large" };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 = "\4\0\5\1\1\11\2\1\1\11\7\1\2\11\3\1"
            + "\1\11\4\1\2\11\2\1\1\11\3\1\1\11\15\1" + "\1\11\1\0\4\1\2\11\3\1\1\0\3\1\2\11"
            + "\2\0\1\11\3\1\1\0\5\1\1\11\6\1\1\11" + "\11\1\1\11\13\1";

    private static int[] zzUnpackAttribute() {
        final int[] result = new int[110];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            final int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /** the input device */
    private java.io.Reader zzReader;

    /** the current state of the DFA */
    private int zzState;

    /** the current lexical state */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /** the textposition at the last accepting state */
    private int zzMarkedPos;

    /** the current text position in the buffer */
    private int zzCurrentPos;

    /** startRead marks the beginning of the yytext() string in the buffer */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read from input
     */
    private int zzEndRead;

    /** number of newlines encountered up to the start of the matched text */
    private int yyline;

    /** the number of characters up to the start of the matched text */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /** zzAtEOF == true <=> the scanner is at the EOF */
    private boolean zzAtEOF;

    /** denotes if the user-EOF-code has already been executed */
    private boolean zzEOFDone;

    /* user code: */

    /**
     * Constructor. This must be here because JFlex does not generate a no-parameter constructor.
     */
    public AExpressionTokenMaker() {}

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param tokenType
     *            The token's type.
     * @see #addToken(int, int, int)
     */
    private void addHyperlinkToken(final int start, final int end, final int tokenType) {
        final int so = start + offsetShift;
        addToken(zzBuffer, start, end, tokenType, so, true);
    }

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param tokenType
     *            The token's type.
     */
    private void addToken(final int tokenType) {
        addToken(zzStartRead, zzMarkedPos - 1, tokenType);
    }

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param tokenType
     *            The token's type.
     * @see #addHyperlinkToken(int, int, int)
     */
    private void addToken(final int start, final int end, final int tokenType) {
        final int so = start + offsetShift;
        addToken(zzBuffer, start, end, tokenType, so, false);
    }

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param array
     *            The character array.
     * @param start
     *            The starting offset in the array.
     * @param end
     *            The ending offset in the array.
     * @param tokenType
     *            The token's type.
     * @param startOffset
     *            The offset in the document at which this token occurs.
     * @param hyperlink
     *            Whether this token is a hyperlink.
     */
    @Override
    public void addToken(final char[] array, final int start, final int end, final int tokenType, final int startOffset,
            final boolean hyperlink) {
        super.addToken(array, start, end, tokenType, startOffset, hyperlink);
        zzStartRead = zzMarkedPos;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] getLineCommentStartAndEnd(final int languageIndex) {
        return new String[] { "//", null };
    }

    /**
     * Returns the first token in the linked list of tokens generated from <code>text</code>. This method must be
     * implemented by subclasses so they can correctly implement syntax highlighting.
     *
     * @param text
     *            The text from which to get tokens.
     * @param initialTokenType
     *            The token type we should start with.
     * @param startOffset
     *            The offset into the document at which <code>text</code> starts.
     * @return The first <code>Token</code> in a linked list representing the syntax highlighted text.
     */
    @Override
    public Token getTokenList(final Segment text, final int initialTokenType, final int startOffset) {

        resetTokenList();
        this.offsetShift = -text.offset + startOffset;

        // Start off in the proper state.
        int state = Token.NULL;
        switch (initialTokenType) {
        case Token.COMMENT_MULTILINE:
            state = MLC;
            start = text.offset;
            break;
        case Token.COMMENT_DOCUMENTATION:
            state = DOCCOMMENT;
            start = text.offset;
            break;
        default:
            state = Token.NULL;
        }

        s = text;
        try {
            yyreset(zzReader);
            yybegin(state);
            return yylex();
        } catch (final IOException ioe) {
            ioe.printStackTrace();
            return new TokenImpl();
        }

    }

    /**
     * Refills the input buffer.
     *
     * @return <code>true</code> if EOF was reached, otherwise <code>false</code>.
     */
    private boolean zzRefill() {
        return zzCurrentPos >= s.offset + s.count;
    }

    /**
     * Resets the scanner to read from a new input stream. Does not close the old reader.
     *
     * All internal variables are reset, the old input stream <b>cannot</b> be reused (internal buffer is discarded and
     * lost). Lexical state is set to <tt>YY_INITIAL</tt>.
     *
     * @param reader
     *            the new input stream
     */
    public final void yyreset(final Reader reader) {
        // 's' has been updated.
        zzBuffer = s.array;
        /*
         * We replaced the line below with the two below it because zzRefill no longer "refills" the buffer (since the
         * way we do it, it's always "full" the first time through, since it points to the segment's array). So, we
         * assign zzEndRead here.
         */
        //zzStartRead = zzEndRead = s.offset;
        zzStartRead = s.offset;
        zzEndRead = zzStartRead + s.count - 1;
        zzCurrentPos = zzMarkedPos = s.offset;
        zzLexicalState = YYINITIAL;
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
    }

    /**
     * Creates a new scanner There is also a java.io.InputStream version of this constructor.
     *
     * @param in
     *            the java.io.Reader to read input from.
     */
    public AExpressionTokenMaker(final java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner. There is also java.io.Reader version of this constructor.
     *
     * @param in
     *            the java.io.Inputstream to read input from.
     */
    public AExpressionTokenMaker(final java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed
     *            the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(final String packed) {
        final char[] map = new char[0x10000];
        int i = 0; /* index in packed string */
        int j = 0; /* index in unpacked array */
        while (i < 172) {
            int count = packed.charAt(i++);
            final char value = packed.charAt(i++);
            do {
                map[j++] = value;
            } while (--count > 0);
        }
        return map;
    }

    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true; /* indicate end of file */
        zzEndRead = zzStartRead; /* invalidate buffer */

        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state
     *
     * @param newState
     *            the new lexical state
     */
    @Override
    public final void yybegin(final int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at position <tt>pos</tt> from the matched text.
     * 
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos
     *            the position of the character to fetch. A value from 0 to yylength()-1.
     *
     * @return the character at position pos
     */
    public final char yycharat(final int pos) {
        return zzBuffer[zzStartRead + pos];
    }

    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occured while scanning.
     *
     * In a wellformed scanner (no or only correct usage of yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen". If this method is called, something is seriously
     * wrong (e.g. a JFlex bug producing a faulty scanner etc.).
     *
     * Usual syntax/scanner level error handling should be done in error fallback rules.
     *
     * @param errorCode
     *            the code of the errormessage to display
     */
    private void zzScanError(final int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (final ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * They will be read again by then next call of the scanning method
     *
     * @param number
     *            the number of characters to be read again. This number must not be greater than yylength()!
     */
    public void yypushback(final int number) {
        if (number > yylength()) {
            zzScanError(ZZ_PUSHBACK_2BIG);
        }

        zzMarkedPos -= number;
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of input is encountered or an I/O-Error
     * occurs.
     *
     * @return the next token
     * @exception java.io.IOException
     *                if any I/O-Error occurs
     */
    public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        final char[] zzCMapL = ZZ_CMAP;

        final int[] zzTransL = ZZ_TRANS;
        final int[] zzRowMapL = ZZ_ROWMAP;
        final int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            zzForAction: {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = zzBufferL[zzCurrentPosL++];
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        final boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    final int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) {
                        break zzForAction;
                    }
                    zzState = zzNext;

                    final int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) {
                            break zzForAction;
                        }
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
            case 5: {
                addNullToken();
                return firstToken;
            }
            case 31:
                break;
            case 26: {
                addToken(Token.LITERAL_CHAR);
            }
            case 32:
                break;
            case 23: {
                yybegin(YYINITIAL);
                addToken(start, zzStartRead + 1, Token.COMMENT_MULTILINE);
            }
            case 33:
                break;
            case 29: {
                addToken(Token.COMMENT_MULTILINE);
            }
            case 34:
                break;
            case 21: {
                start = zzMarkedPos - 2;
                yybegin(MLC);
            }
            case 35:
                break;
            case 7: {
                addToken(Token.WHITESPACE);
            }
            case 36:
                break;
            case 17: {
                addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
            }
            case 37:
                break;
            case 27: {
                addToken(Token.ERROR_STRING_DOUBLE);
            }
            case 38:
                break;
            case 16: {
                addToken(Token.LITERAL_NUMBER_FLOAT);
            }
            case 39:
                break;
            case 22: {
                addToken(Token.RESERVED_WORD);
            }
            case 40:
                break;
            case 9: {
                addToken(Token.SEPARATOR);
            }
            case 41:
                break;
            case 2: {
                addToken(Token.IDENTIFIER);
            }
            case 42:
                break;
            case 14: {
                addToken(start, zzStartRead - 1, Token.COMMENT_EOL);
                addNullToken();
                return firstToken;
            }
            case 43:
                break;
            case 20: {
                start = zzMarkedPos - 2;
                yybegin(EOL_COMMENT);
            }
            case 44:
                break;
            case 4: {
                addToken(Token.ERROR_CHAR);
                addNullToken();
                return firstToken;
            }
            case 45:
                break;
            case 6: {
                addToken(Token.ERROR_STRING_DOUBLE);
                addNullToken();
                return firstToken;
            }
            case 46:
                break;
            case 1: {
                addToken(Token.ERROR_IDENTIFIER);
            }
            case 47:
                break;
            case 18: {
                addToken(Token.ERROR_CHAR);
            }
            case 48:
                break;
            case 30: {
                addToken(Token.LITERAL_BOOLEAN);
            }
            case 49:
                break;
            case 13: {
                addToken(start, zzStartRead - 1, Token.COMMENT_DOCUMENTATION);
                return firstToken;
            }
            case 50:
                break;
            case 10: {
                addToken(Token.ANNOTATION);
            }
            case 51:
                break;
            case 28: {
                start = zzMarkedPos - 3;
                yybegin(DOCCOMMENT);
            }
            case 52:
                break;
            case 19: {
                addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
            }
            case 53:
                break;
            case 25: {
                final int temp = zzStartRead;
                addToken(start, zzStartRead - 1, Token.COMMENT_DOCUMENTATION);
                addToken(temp, zzMarkedPos - 1, Token.COMMENT_MARKUP);
                start = zzMarkedPos;
            }
            case 54:
                break;
            case 24: {
                yybegin(YYINITIAL);
                addToken(start, zzStartRead + 1, Token.COMMENT_DOCUMENTATION);
            }
            case 55:
                break;
            case 15: {
                addToken(Token.ERROR_NUMBER_FORMAT);
            }
            case 56:
                break;
            case 3: {
                addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
            }
            case 57:
                break;
            case 8: {
                addToken(Token.OPERATOR);
            }
            case 58:
                break;
            case 11: {
            }
            case 59:
                break;
            case 12: {
                addToken(start, zzStartRead - 1, Token.COMMENT_MULTILINE);
                return firstToken;
            }
            case 60:
                break;
            default:
                if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                    zzAtEOF = true;
                    switch (zzLexicalState) {
                    case EOL_COMMENT: {
                        addToken(start, zzStartRead - 1, Token.COMMENT_EOL);
                        addNullToken();
                        return firstToken;
                    }
                    case 111:
                        break;
                    case DOCCOMMENT: {
                        yybegin(YYINITIAL);
                        addToken(start, zzEndRead, Token.COMMENT_DOCUMENTATION);
                        return firstToken;
                    }
                    case 112:
                        break;
                    case YYINITIAL: {
                        addNullToken();
                        return firstToken;
                    }
                    case 113:
                        break;
                    case MLC: {
                        addToken(start, zzStartRead - 1, Token.COMMENT_MULTILINE);
                        return firstToken;
                    }
                    case 114:
                        break;
                    default:
                        return null;
                    }
                } else {
                    zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

}
