/* The following code was generated by JFlex 1.4.3 on 11.05.19, 15:17 */

package de.invesdwin.context.client.swing.rsyntaxtextarea.expression.internal;

import java.io.IOException;
import java.io.Reader;

import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexCTokenMaker;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenImpl;

// CHECKSTYLE:OFF
// @NotThreadSafe

/**
 * This class is a scanner generated by <a href="http://www.jflex.de/">JFlex</a> 1.4.3 on 11.05.19, 15:17 from the
 * specification file
 * <tt>/opt/subes/dev/Entwicklung/invesdwin/invesdwin-oss/invesdwin-context-client/invesdwin-context-client-parent/invesdwin-context-client-swing-rsyntaxtextarea/src/main/java/de/invesdwin/context/client/swing/rsyntaxtextarea/expression/internal/ExpressionTokenMaker.flex</tt>
 */
public abstract class AExpressionTokenMaker extends AbstractJFlexCTokenMaker {

    /** This character denotes the end of file */
    public static final int YYEOF = -1;

    /** initial size of the lookahead buffer */
    private static final int ZZ_BUFFERSIZE = 16384;

    /** lexical states */
    public static final int EOL_COMMENT = 6;
    public static final int DOCCOMMENT = 4;
    public static final int YYINITIAL = 0;
    public static final int MLC = 2;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l ZZ_LEXSTATE[l+1] is the state in the DFA for the
     * lexical state l at the beginning of a line l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = { 0, 0, 1, 1, 2, 2, 3, 3 };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED = "\11\0\1\22\1\11\1\0\1\22\1\20\22\0\1\22\1\52\1\16"
            + "\1\21\1\21\1\52\1\55\1\10\2\45\1\24\1\47\1\46\1\33" + "\1\34\1\23\1\4\1\5\2\17\4\7\2\3\1\46\1\46\1\50"
            + "\1\51\1\53\1\54\1\62\1\43\1\26\1\6\1\31\1\32\1\42" + "\5\1\1\25\1\1\1\56\1\57\2\1\1\37\1\44\1\35\1\41"
            + "\2\1\1\30\2\1\1\45\1\12\1\45\1\52\1\2\1\0\1\43" + "\1\27\1\6\1\31\1\32\1\15\1\1\1\60\3\1\1\25\1\1"
            + "\1\14\1\57\2\1\1\40\1\44\1\36\1\13\1\1\1\60\1\30" + "\2\1\1\61\1\52\1\45\1\54\uff81\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 = "\4\0\1\1\1\2\2\3\1\4\1\5\1\2\1\6"
            + "\1\1\1\7\3\10\3\2\1\11\1\2\5\10\1\2" + "\1\12\1\13\3\12\1\14\3\12\1\15\1\1\2\16"
            + "\1\17\1\3\1\16\1\17\2\16\1\20\2\16\1\4" + "\1\21\1\0\1\4\1\2\2\6\1\22\1\23\1\24"
            + "\2\2\1\0\1\10\1\25\1\26\1\27\2\0\1\30" + "\1\1\1\3\1\17\1\0\2\20\1\3\1\20\1\4"
            + "\1\31\2\4\1\21\1\4\1\2\1\6\1\32\1\6" + "\1\33\1\2\1\1\2\16\1\4\1\6\1\34\1\35"
            + "\1\1\1\4\1\6\1\1\1\4\1\6";

    private static int[] zzUnpackAction() {
        final int[] result = new int[103];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            final int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 = "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"
            + "\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u01cb\0\u0264\0\u0297\0\u02ca"
            + "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u01cb\0\u01cb\0\u03c9\0\u03fc"
            + "\0\u042f\0\u01cb\0\u0462\0\u0495\0\u04c8\0\u01cb\0\u01cb\0\u04fb"
            + "\0\u052e\0\u01cb\0\u0561\0\u0594\0\u05c7\0\u01cb\0\u05fa\0\u062d"
            + "\0\u0660\0\u062d\0\u062d\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f"
            + "\0\u0792\0\u07c5\0\u07f8\0\u01cb\0\u082b\0\u085e\0\u0891\0\u08c4"
            + "\0\u08f7\0\u01cb\0\u01cb\0\u092a\0\u095d\0\u0990\0\u02ca\0\u09c3"
            + "\0\377\0\u01cb\0\u01cb\0\u09f6\0\u0a29\0\u01cb\0\u0a5c\0\u0a8f"
            + "\0\u0ac2\0\u0af5\0\u0b28\0\u062d\0\u0b5b\0\u0b8e\0\u0bc1\0\u01cb"
            + "\0\u0bf4\0\u0c27\0\u082b\0\u0c5a\0\u0c8d\0\u0cc0\0\u01cb\0\u0cf3"
            + "\0\u0d26\0\u0d59\0\u0d8c\0\u0b5b\0\u0dbf\0\u0df2\0\u0e25\0\u01cb"
            + "\0\377\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57";

    private static int[] zzUnpackRowMap() {
        final int[] result = new int[103];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            final int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 = "\1\5\2\6\1\7\1\10\1\7\1\6\1\7\1\11"
            + "\1\12\1\5\2\6\1\13\1\14\1\7\1\15\1\6" + "\1\16\1\17\1\20\6\6\1\21\1\22\2\23\3\6"
            + "\1\13\1\24\1\6\1\25\1\26\1\27\1\30\2\20" + "\1\31\1\32\1\33\1\6\1\34\1\6\1\25\1\26"
            + "\11\35\1\36\3\35\1\37\6\35\1\40\33\35\1\37" + "\2\35\11\41\1\42\3\41\1\37\6\41\1\43\23\41"
            + "\1\44\7\41\2\37\1\0\11\45\1\46\3\45\1\37" + "\42\45\1\37\2\45\10\5\2\0\4\5\1\0\1\5"
            + "\1\0\1\5\3\0\6\5\2\0\10\5\11\0\3\5" + "\2\0\1\5\7\6\2\0\1\47\3\6\1\0\1\6"
            + "\1\0\1\6\3\0\6\6\2\0\10\6\11\0\3\6" + "\2\0\2\50\1\51\3\7\1\50\1\7\2\0\3\50"
            + "\1\52\1\0\1\7\1\0\1\50\3\0\1\53\3\50" + "\1\52\1\54\1\0\1\55\5\50\1\52\2\50\11\0"
            + "\3\50\2\0\2\50\1\56\1\57\2\60\1\50\1\60" + "\2\0\3\50\1\52\1\0\1\60\1\0\1\50\3\0"
            + "\1\53\2\61\1\62\1\52\1\54\1\0\1\55\5\50" + "\1\52\2\50\11\0\3\50\2\0\10\63\1\64\1\65"
            + "\1\66\50\63\63\0\1\5\7\6\2\0\1\47\3\6" + "\1\0\1\6\1\0\1\6\3\0\6\6\2\0\6\6"
            + "\1\67\1\6\11\0\3\6\2\0\11\14\1\70\1\71" + "\3\14\1\72\44\14\22\0\1\16\63\0\1\73\1\74"
            + "\24\0\1\32\62\0\1\32\44\0\1\32\15\0\1\32" + "\14\0\3\55\1\0\1\55\7\0\1\55\43\0\1\5"
            + "\7\6\2\0\1\47\3\6\1\0\1\6\1\0\1\6" + "\3\0\6\6\2\0\2\6\2\75\4\6\11\0\3\6"
            + "\2\0\1\5\7\6\2\0\1\47\1\6\1\76\1\6" + "\1\0\1\6\1\0\1\6\3\0\6\6\2\0\10\6"
            + "\11\0\1\76\2\6\51\0\1\32\1\0\1\32\61\0" + "\1\77\1\32\1\0\1\32\57\0\2\32\1\0\1\100"
            + "\60\0\1\32\3\0\1\32\5\0\1\5\7\6\2\0" + "\1\47\3\6\1\0\1\6\1\0\1\6\3\0\6\6"
            + "\2\0\2\6\2\101\4\6\11\0\3\6\2\0\11\35" + "\1\0\3\35\1\0\6\35\1\0\33\35\1\0\2\35"
            + "\23\0\1\102\37\0\11\41\1\0\3\41\1\0\6\41" + "\1\0\23\41\1\0\7\41\26\0\1\103\40\0\1\104"
            + "\4\0\1\104\4\0\3\104\5\0\1\105\1\0\6\104" + "\2\0\10\104\6\0\1\106\2\0\3\104\2\0\11\45"
            + "\1\0\3\45\1\0\42\45\1\0\2\45\10\5\2\0" + "\1\5\1\107\2\5\1\0\1\5\1\0\1\5\3\0"
            + "\6\5\2\0\10\5\11\0\3\5\2\0\10\50\2\0" + "\4\50\1\0\1\50\1\0\1\50\3\0\6\50\2\0"
            + "\10\50\11\0\3\50\2\0\2\50\1\51\3\110\1\50" + "\1\110\2\0\4\50\1\0\1\110\1\0\1\50\3\0"
            + "\6\50\2\0\10\50\11\0\3\50\2\0\3\50\3\111" + "\1\50\1\111\2\0\4\50\1\0\1\111\1\0\1\50"
            + "\3\0\6\50\1\112\1\0\10\50\2\0\1\112\6\0" + "\3\50\2\0\3\50\3\55\1\50\1\55\2\0\3\50"
            + "\1\52\1\0\1\55\1\0\1\50\3\0\4\50\1\52" + "\1\54\2\0\5\50\1\52\2\50\11\0\3\50\2\0"
            + "\2\50\1\56\1\50\2\113\1\50\1\113\2\0\4\50" + "\1\0\1\113\1\0\1\50\3\0\6\50\2\0\10\50"
            + "\11\0\3\50\2\0\3\50\3\57\1\50\1\57\2\0" + "\3\50\1\52\1\0\1\57\1\0\1\50\3\0\4\50"
            + "\1\52\1\54\1\0\1\55\5\50\1\52\2\50\11\0" + "\3\50\2\0\2\50\1\56\1\57\2\60\1\50\1\60"
            + "\2\0\3\50\1\52\1\0\1\60\1\0\1\50\3\0" + "\1\114\3\50\1\52\1\54\1\0\1\55\5\50\1\52"
            + "\2\50\11\0\3\50\2\0\4\50\2\115\2\50\2\0" + "\4\50\1\0\1\50\1\0\1\50\3\0\6\50\2\0"
            + "\10\50\11\0\3\50\2\0\3\50\5\116\2\0\3\50" + "\1\116\1\0\1\116\1\0\1\50\3\0\1\50\2\116"
            + "\1\50\2\116\2\0\5\50\2\116\1\50\11\0\3\50" + "\2\0\10\117\1\120\1\0\51\117\10\0\1\120\52\0"
            + "\4\117\2\121\1\117\1\122\1\123\1\0\1\63\1\124" + "\3\63\1\121\7\117\1\63\6\117\1\63\1\117\1\63"
            + "\22\117\1\5\7\6\2\0\1\47\3\6\1\0\1\6" + "\1\0\1\6\3\0\1\125\5\6\2\0\10\6\11\0"
            + "\3\6\2\0\12\70\1\126\3\70\1\127\50\70\2\14" + "\1\70\2\14\1\0\1\14\1\130\4\14\7\70\1\14"
            + "\6\70\1\14\1\70\1\14\22\70\24\0\1\131\36\0" + "\1\5\7\6\2\0\1\47\1\132\2\6\1\0\1\6"
            + "\1\0\1\6\3\0\6\6\2\0\4\6\1\132\3\6" + "\11\0\3\6\2\0\1\5\7\6\2\0\1\47\3\6"
            + "\1\0\1\6\1\0\1\6\3\0\4\6\1\101\1\6" + "\2\0\10\6\11\0\3\6\53\0\1\32\1\0\1\20"
            + "\7\0\53\104\1\106\7\104\1\0\1\104\4\0\1\104" + "\4\0\3\104\7\0\6\104\2\0\10\104\6\0\1\106"
            + "\2\0\3\104\2\0\3\5\5\133\2\0\3\5\1\133" + "\1\0\1\133\1\0\1\5\3\0\1\5\2\133\1\5"
            + "\2\133\2\0\5\5\2\133\1\5\11\0\3\5\2\0" + "\2\50\1\51\3\110\1\50\1\110\2\0\4\50\1\0"
            + "\1\110\1\0\1\50\3\0\1\53\5\50\2\0\10\50" + "\11\0\3\50\2\0\3\50\3\111\1\50\1\111\2\0"
            + "\3\50\1\52\1\0\1\111\1\0\1\50\3\0\4\50" + "\1\52\1\50\2\0\5\50\1\52\2\50\11\0\3\50"
            + "\5\0\3\111\1\0\1\111\7\0\1\111\43\0\2\50" + "\1\56\1\50\2\113\1\50\1\113\2\0\4\50\1\0"
            + "\1\113\1\0\1\50\3\0\1\114\5\50\2\0\10\50" + "\11\0\3\50\2\0\2\50\1\134\1\50\2\115\2\50"
            + "\2\0\4\50\1\0\1\50\1\0\1\50\3\0\6\50" + "\2\0\10\50\11\0\3\50\2\0\2\50\1\135\5\116"
            + "\2\0\3\50\1\116\1\0\1\116\1\0\1\50\3\0" + "\1\114\2\116\1\50\2\116\2\0\5\50\2\116\1\50"
            + "\11\0\3\50\2\0\10\117\1\64\1\0\55\117\2\122" + "\1\117\1\122\1\120\1\0\5\117\1\122\47\117\2\63"
            + "\1\117\1\63\1\120\1\0\5\117\1\63\46\117\5\136" + "\1\64\1\0\3\117\1\136\1\117\1\136\6\117\2\136"
            + "\1\117\2\136\7\117\2\136\17\117\1\5\7\6\2\0" + "\1\47\3\6\1\0\1\6\1\0\1\6\3\0\6\6"
            + "\2\0\7\6\1\132\11\0\3\6\2\0\11\70\1\0" + "\54\70\5\137\2\70\1\126\2\70\1\137\1\127\1\137"
            + "\6\70\2\137\1\70\2\137\7\70\2\137\17\70\23\0" + "\1\140\37\0\1\5\7\6\2\0\1\47\3\6\1\0"
            + "\1\6\1\0\1\6\3\0\5\6\1\141\2\0\10\6" + "\11\0\3\6\2\0\3\5\5\142\2\0\3\5\1\142"
            + "\1\0\1\142\1\0\1\5\3\0\1\5\2\142\1\5" + "\2\142\2\0\5\5\2\142\1\5\11\0\3\5\2\0"
            + "\2\50\1\135\5\116\2\0\3\50\1\116\1\0\1\116" + "\1\0\1\50\3\0\1\50\2\116\1\50\2\116\2\0"
            + "\5\50\2\116\1\50\11\0\3\50\2\0\3\117\5\143" + "\1\64\1\0\3\117\1\143\1\117\1\143\6\117\2\143"
            + "\1\117\2\143\7\117\2\143\17\117\3\70\5\144\2\70" + "\1\126\2\70\1\144\1\127\1\144\6\70\2\144\1\70"
            + "\2\144\7\70\2\144\17\70\3\5\5\145\2\0\3\5" + "\1\145\1\0\1\145\1\0\1\5\3\0\1\5\2\145"
            + "\1\5\2\145\2\0\5\5\2\145\1\5\11\0\3\5" + "\2\0\3\117\5\146\1\64\1\0\3\117\1\146\1\117"
            + "\1\146\6\117\2\146\1\117\2\146\7\117\2\146\17\117" + "\3\70\5\147\2\70\1\126\2\70\1\147\1\127\1\147"
            + "\6\70\2\147\1\70\2\147\7\70\2\147\17\70\3\5" + "\5\6\2\0\3\5\1\6\1\0\1\6\1\0\1\5"
            + "\3\0\1\5\2\6\1\5\2\6\2\0\5\5\2\6" + "\1\5\11\0\3\5\2\0\3\117\5\63\1\64\1\0"
            + "\3\117\1\63\1\117\1\63\6\117\2\63\1\117\2\63" + "\7\117\2\63\17\117\3\70\5\14\2\70\1\126\2\70"
            + "\1\14\1\127\1\14\6\70\2\14\1\70\2\14\7\70" + "\2\14\17\70";

    private static int[] zzUnpackTrans() {
        final int[] result = new int[3978];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = { "Unkown internal scanner error", "Error: could not match input",
            "Error: pushback value was too large" };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 = "\4\0\5\1\1\11\2\1\1\11\7\1\2\11\3\1"
            + "\1\11\3\1\2\11\2\1\1\11\3\1\1\11\15\1" + "\1\11\1\0\4\1\2\11\3\1\1\0\2\1\2\11"
            + "\2\0\1\11\3\1\1\0\5\1\1\11\6\1\1\11" + "\10\1\1\11\7\1";

    private static int[] zzUnpackAttribute() {
        final int[] result = new int[103];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(final String packed, final int offset, final int[] result) {
        int i = 0; /* index in packed string */
        int j = offset; /* index in unpacked array */
        final int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            final int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /** the input device */
    private java.io.Reader zzReader;

    /** the current state of the DFA */
    private int zzState;

    /** the current lexical state */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /** the textposition at the last accepting state */
    private int zzMarkedPos;

    /** the current text position in the buffer */
    private int zzCurrentPos;

    /** startRead marks the beginning of the yytext() string in the buffer */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read from input
     */
    private int zzEndRead;

    /** number of newlines encountered up to the start of the matched text */
    private int yyline;

    /** the number of characters up to the start of the matched text */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /** zzAtEOF == true <=> the scanner is at the EOF */
    private boolean zzAtEOF;

    /** denotes if the user-EOF-code has already been executed */
    private boolean zzEOFDone;

    /* user code: */

    /**
     * Constructor. This must be here because JFlex does not generate a no-parameter constructor.
     */
    public AExpressionTokenMaker() {}

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param tokenType
     *            The token's type.
     */
    private void addToken(final int tokenType) {
        addToken(zzStartRead, zzMarkedPos - 1, tokenType);
    }

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param tokenType
     *            The token's type.
     * @see #addHyperlinkToken(int, int, int)
     */
    private void addToken(final int start, final int end, final int tokenType) {
        final int so = start + offsetShift;
        addToken(zzBuffer, start, end, tokenType, so, false);
    }

    /**
     * Adds the token specified to the current linked list of tokens.
     *
     * @param array
     *            The character array.
     * @param start
     *            The starting offset in the array.
     * @param end
     *            The ending offset in the array.
     * @param tokenType
     *            The token's type.
     * @param startOffset
     *            The offset in the document at which this token occurs.
     * @param hyperlink
     *            Whether this token is a hyperlink.
     */
    @Override
    public void addToken(final char[] array, final int start, final int end, final int tokenType, final int startOffset,
            final boolean hyperlink) {
        super.addToken(array, start, end, tokenType, startOffset, hyperlink);
        zzStartRead = zzMarkedPos;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] getLineCommentStartAndEnd(final int languageIndex) {
        return new String[] { "//", null };
    }

    /**
     * Returns the first token in the linked list of tokens generated from <code>text</code>. This method must be
     * implemented by subclasses so they can correctly implement syntax highlighting.
     *
     * @param text
     *            The text from which to get tokens.
     * @param initialTokenType
     *            The token type we should start with.
     * @param startOffset
     *            The offset into the document at which <code>text</code> starts.
     * @return The first <code>Token</code> in a linked list representing the syntax highlighted text.
     */
    @Override
    public Token getTokenList(final Segment text, final int initialTokenType, final int startOffset) {

        resetTokenList();
        this.offsetShift = -text.offset + startOffset;

        // Start off in the proper state.
        int state = Token.NULL;
        switch (initialTokenType) {
        case Token.COMMENT_MULTILINE:
            state = MLC;
            start = text.offset;
            break;
        case Token.COMMENT_DOCUMENTATION:
            state = DOCCOMMENT;
            start = text.offset;
            break;
        default:
            state = Token.NULL;
        }

        s = text;
        try {
            yyreset(zzReader);
            yybegin(state);
            return yylex();
        } catch (final IOException ioe) {
            ioe.printStackTrace();
            return new TokenImpl();
        }

    }

    /**
     * Refills the input buffer.
     *
     * @return <code>true</code> if EOF was reached, otherwise <code>false</code>.
     */
    private boolean zzRefill() {
        return zzCurrentPos >= s.offset + s.count;
    }

    /**
     * Resets the scanner to read from a new input stream. Does not close the old reader.
     *
     * All internal variables are reset, the old input stream <b>cannot</b> be reused (internal buffer is discarded and
     * lost). Lexical state is set to <tt>YY_INITIAL</tt>.
     *
     * @param reader
     *            the new input stream
     */
    public final void yyreset(final Reader reader) {
        // 's' has been updated.
        zzBuffer = s.array;
        /*
         * We replaced the line below with the two below it because zzRefill no longer "refills" the buffer (since the
         * way we do it, it's always "full" the first time through, since it points to the segment's array). So, we
         * assign zzEndRead here.
         */
        //zzStartRead = zzEndRead = s.offset;
        zzStartRead = s.offset;
        zzEndRead = zzStartRead + s.count - 1;
        zzCurrentPos = zzMarkedPos = s.offset;
        zzLexicalState = YYINITIAL;
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
    }

    /**
     * Creates a new scanner There is also a java.io.InputStream version of this constructor.
     *
     * @param in
     *            the java.io.Reader to read input from.
     */
    public AExpressionTokenMaker(final java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner. There is also java.io.Reader version of this constructor.
     *
     * @param in
     *            the java.io.Inputstream to read input from.
     */
    public AExpressionTokenMaker(final java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed
     *            the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(final String packed) {
        final char[] map = new char[0x10000];
        int i = 0; /* index in packed string */
        int j = 0; /* index in unpacked array */
        while (i < 172) {
            int count = packed.charAt(i++);
            final char value = packed.charAt(i++);
            do {
                map[j++] = value;
            } while (--count > 0);
        }
        return map;
    }

    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true; /* indicate end of file */
        zzEndRead = zzStartRead; /* invalidate buffer */

        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state
     *
     * @param newState
     *            the new lexical state
     */
    @Override
    public final void yybegin(final int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at position <tt>pos</tt> from the matched text.
     * 
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos
     *            the position of the character to fetch. A value from 0 to yylength()-1.
     *
     * @return the character at position pos
     */
    public final char yycharat(final int pos) {
        return zzBuffer[zzStartRead + pos];
    }

    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occured while scanning.
     *
     * In a wellformed scanner (no or only correct usage of yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen". If this method is called, something is seriously
     * wrong (e.g. a JFlex bug producing a faulty scanner etc.).
     *
     * Usual syntax/scanner level error handling should be done in error fallback rules.
     *
     * @param errorCode
     *            the code of the errormessage to display
     */
    private void zzScanError(final int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (final ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * They will be read again by then next call of the scanning method
     *
     * @param number
     *            the number of characters to be read again. This number must not be greater than yylength()!
     */
    public void yypushback(final int number) {
        if (number > yylength()) {
            zzScanError(ZZ_PUSHBACK_2BIG);
        }

        zzMarkedPos -= number;
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of input is encountered or an I/O-Error
     * occurs.
     *
     * @return the next token
     * @exception java.io.IOException
     *                if any I/O-Error occurs
     */
    public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        final char[] zzCMapL = ZZ_CMAP;

        final int[] zzTransL = ZZ_TRANS;
        final int[] zzRowMapL = ZZ_ROWMAP;
        final int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            zzForAction: {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = zzBufferL[zzCurrentPosL++];
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        final boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    final int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) {
                        break zzForAction;
                    }
                    zzState = zzNext;

                    final int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) {
                            break zzForAction;
                        }
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
            case 5: {
                addNullToken();
                return firstToken;
            }
            case 30:
                break;
            case 25: {
                addToken(Token.LITERAL_CHAR);
            }
            case 31:
                break;
            case 22: {
                yybegin(YYINITIAL);
                addToken(start, zzStartRead + 1, Token.COMMENT_MULTILINE);
            }
            case 32:
                break;
            case 28: {
                addToken(Token.COMMENT_MULTILINE);
            }
            case 33:
                break;
            case 20: {
                start = zzMarkedPos - 2;
                yybegin(MLC);
            }
            case 34:
                break;
            case 7: {
                addToken(Token.WHITESPACE);
            }
            case 35:
                break;
            case 16: {
                addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
            }
            case 36:
                break;
            case 26: {
                addToken(Token.ERROR_STRING_DOUBLE);
            }
            case 37:
                break;
            case 15: {
                addToken(Token.LITERAL_NUMBER_FLOAT);
            }
            case 38:
                break;
            case 21: {
                addToken(Token.RESERVED_WORD);
            }
            case 39:
                break;
            case 9: {
                addToken(Token.SEPARATOR);
            }
            case 40:
                break;
            case 2: {
                addToken(Token.IDENTIFIER);
            }
            case 41:
                break;
            case 13: {
                addToken(start, zzStartRead - 1, Token.COMMENT_EOL);
                addNullToken();
                return firstToken;
            }
            case 42:
                break;
            case 19: {
                start = zzMarkedPos - 2;
                yybegin(EOL_COMMENT);
            }
            case 43:
                break;
            case 4: {
                addToken(Token.ERROR_CHAR);
                addNullToken();
                return firstToken;
            }
            case 44:
                break;
            case 6: {
                addToken(Token.ERROR_STRING_DOUBLE);
                addNullToken();
                return firstToken;
            }
            case 45:
                break;
            case 1: {
                addToken(Token.ERROR_IDENTIFIER);
            }
            case 46:
                break;
            case 17: {
                addToken(Token.ERROR_CHAR);
            }
            case 47:
                break;
            case 29: {
                addToken(Token.LITERAL_BOOLEAN);
            }
            case 48:
                break;
            case 12: {
                addToken(start, zzStartRead - 1, Token.COMMENT_DOCUMENTATION);
                return firstToken;
            }
            case 49:
                break;
            case 27: {
                start = zzMarkedPos - 3;
                yybegin(DOCCOMMENT);
            }
            case 50:
                break;
            case 18: {
                addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
            }
            case 51:
                break;
            case 24: {
                final int temp = zzStartRead;
                addToken(start, zzStartRead - 1, Token.COMMENT_DOCUMENTATION);
                addToken(temp, zzMarkedPos - 1, Token.COMMENT_MARKUP);
                start = zzMarkedPos;
            }
            case 52:
                break;
            case 23: {
                yybegin(YYINITIAL);
                addToken(start, zzStartRead + 1, Token.COMMENT_DOCUMENTATION);
            }
            case 53:
                break;
            case 14: {
                addToken(Token.ERROR_NUMBER_FORMAT);
            }
            case 54:
                break;
            case 3: {
                addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
            }
            case 55:
                break;
            case 8: {
                addToken(Token.OPERATOR);
            }
            case 56:
                break;
            case 10: {
            }
            case 57:
                break;
            case 11: {
                addToken(start, zzStartRead - 1, Token.COMMENT_MULTILINE);
                return firstToken;
            }
            case 58:
                break;
            default:
                if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                    zzAtEOF = true;
                    switch (zzLexicalState) {
                    case EOL_COMMENT: {
                        addToken(start, zzStartRead - 1, Token.COMMENT_EOL);
                        addNullToken();
                        return firstToken;
                    }
                    case 104:
                        break;
                    case DOCCOMMENT: {
                        yybegin(YYINITIAL);
                        addToken(start, zzEndRead, Token.COMMENT_DOCUMENTATION);
                        return firstToken;
                    }
                    case 105:
                        break;
                    case YYINITIAL: {
                        addNullToken();
                        return firstToken;
                    }
                    case 106:
                        break;
                    case MLC: {
                        addToken(start, zzStartRead - 1, Token.COMMENT_MULTILINE);
                        return firstToken;
                    }
                    case 107:
                        break;
                    default:
                        return null;
                    }
                } else {
                    zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

}
